// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PXCAFDoc_Color.jxx>

IMPLEMENT_DOWNCAST(PXCAFDoc_Color,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PXCAFDoc_Color)



