// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PNaming_Naming_1.jxx>

IMPLEMENT_DOWNCAST(PNaming_Naming_1,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PNaming_Naming_1)



