// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DBC_VArrayNodeOfVArrayOfExtCharacter.hxx>

#include <DBC_VArrayOfExtCharacter.hxx>
#include <DBC_VArrayTNodeOfVArrayOfExtCharacter.hxx>

 


IMPLEMENT_DOWNCAST(DBC_VArrayNodeOfVArrayOfExtCharacter,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(DBC_VArrayNodeOfVArrayOfExtCharacter)


#define Item Standard_ExtCharacter
#define Item_hxx <Standard_ExtCharacter.hxx>
#define DBC_VArrayNode DBC_VArrayNodeOfVArrayOfExtCharacter
#define DBC_VArrayNode_hxx <DBC_VArrayNodeOfVArrayOfExtCharacter.hxx>
#define DBC_VArrayTNode DBC_VArrayTNodeOfVArrayOfExtCharacter
#define DBC_VArrayTNode_hxx <DBC_VArrayTNodeOfVArrayOfExtCharacter.hxx>
#define Handle_DBC_VArrayNode Handle_DBC_VArrayNodeOfVArrayOfExtCharacter
#define DBC_VArrayNode_Type_() DBC_VArrayNodeOfVArrayOfExtCharacter_Type_()
#define DBC_VArray DBC_VArrayOfExtCharacter
#define DBC_VArray_hxx <DBC_VArrayOfExtCharacter.hxx>
#include <DBC_VArrayNode.gxx>

