// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DBC_VArrayNodeOfVArrayOfReal.hxx>

#include <DBC_VArrayOfReal.hxx>
#include <DBC_VArrayTNodeOfVArrayOfReal.hxx>

 


IMPLEMENT_DOWNCAST(DBC_VArrayNodeOfVArrayOfReal,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(DBC_VArrayNodeOfVArrayOfReal)


#define Item Standard_Real
#define Item_hxx <Standard_Real.hxx>
#define DBC_VArrayNode DBC_VArrayNodeOfVArrayOfReal
#define DBC_VArrayNode_hxx <DBC_VArrayNodeOfVArrayOfReal.hxx>
#define DBC_VArrayTNode DBC_VArrayTNodeOfVArrayOfReal
#define DBC_VArrayTNode_hxx <DBC_VArrayTNodeOfVArrayOfReal.hxx>
#define Handle_DBC_VArrayNode Handle_DBC_VArrayNodeOfVArrayOfReal
#define DBC_VArrayNode_Type_() DBC_VArrayNodeOfVArrayOfReal_Type_()
#define DBC_VArray DBC_VArrayOfReal
#define DBC_VArray_hxx <DBC_VArrayOfReal.hxx>
#include <DBC_VArrayNode.gxx>

