// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _DBC_BaseArray_HeaderFile
#define _DBC_BaseArray_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <Standard_Integer.hxx>
#include <DBC_DBVArray.hxx>
#include <Standard_Address.hxx>
class Standard_NullObject;
class Standard_NegativeValue;
class Standard_DimensionMismatch;



class DBC_BaseArray 
{
public:

  DEFINE_STANDARD_ALLOC

  
  //! Creates an BaseArray of NULL size
  Standard_EXPORT DBC_BaseArray();
  
  //! Creates  an BaseArray of lower bound 0 and
  //! upper bound <Size>-1.
  Standard_EXPORT DBC_BaseArray(const Standard_Integer Size);
  
  //! Creates an array which  is the copy of the given
  //! argument.
  Standard_EXPORT DBC_BaseArray(const DBC_BaseArray& BaseArray);
  Standard_EXPORT virtual ~DBC_BaseArray();
  
      Standard_Integer Length()  const;
  
  //! Returns the upper bound
      Standard_Integer Upper()  const;
  
  //! Locks the array <me> in memory and
  //! returns its virtual address
  Standard_EXPORT   Standard_Address Lock()  const;
  
  //! unlocks the array <me> from memory
  Standard_EXPORT   void Unlock()  const;




protected:



  Standard_Integer mySize;
  DBC_DBVArray myData;


private:





};


#include <DBC_BaseArray.lxx>





#endif // _DBC_BaseArray_HeaderFile
