// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ObjMgt_ExternShareable.jxx>

IMPLEMENT_DOWNCAST(ObjMgt_ExternShareable,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(ObjMgt_ExternShareable)



