// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PCollection_HExtendedString.jxx>

IMPLEMENT_DOWNCAST(PCollection_HExtendedString,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PCollection_HExtendedString)



