// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PDataStd_NoteBook.jxx>

IMPLEMENT_DOWNCAST(PDataStd_NoteBook,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PDataStd_NoteBook)



