// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PDF_Reference.jxx>

IMPLEMENT_DOWNCAST(PDF_Reference,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PDF_Reference)



