// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PCDMShape_Document.jxx>

IMPLEMENT_DOWNCAST(PCDMShape_Document,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PCDMShape_Document)



