// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PBRep_TFace1.jxx>

IMPLEMENT_DOWNCAST(PBRep_TFace1,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PBRep_TFace1)



