// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PGeom_RectangularTrimmedSurface.jxx>

IMPLEMENT_DOWNCAST(PGeom_RectangularTrimmedSurface,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PGeom_RectangularTrimmedSurface)



